# Use postgres/example user/password credentials
version: '3.1'

services:
  server:
    build: ../server/
    restart: always
    environment:
      APP_KEY: 8d5ca149e4e94f77b7320f5f5004ea65
      APP_NAME: server
      NODE_ENV: production
      PORT: 3333
      DB_CONNECTION: pg
      PG_HOST: localhost
      PG_PORT: 5433
      PG_USER: pg
      PG_PASSWORD: azerty
      PG_DB_NAME: photos
      DRIVE_DISK: local
      TZ: UTC
    ports:
      - "5433:5432"
  db:
    #build: .
    image: postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      PG_USER: postgre
      PG_PASSWORD: azerty
    ports:
      - "5433:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
  minio:
    image: 'bitnami/minio:latest'
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ACCESS_KEY=minio_access_key
      - MINIO_SECRET_KEY=minio_secret_key
      - MINIO_DEFAULT_BUCKETS=photos:public